#!/bin/bash
# wget -O - https://raw.githubusercontent.com/quatmo/runesq/main/basic | sh
/usr/bin/sudo echo "deb http://deb.debian.org/debian buster main" | sudo tee -a /etc/apt/sources.list
/usr/bin/sudo echo "deb-src http://deb.debian.org/debian buster main" | sudo tee -a /etc/apt/sources.list
sleep 0.3
/usr/bin/sudo apt-get update
sleep 0.3
/usr/bin/sudo apt-get install -y fuse3
sleep 0.3
/usr/bin/sudo apt-get install -y mc
sleep 0.3
/usr/bin/sudo apt-get install -y htop
sleep 0.3
sudo apt-get install -y default-jre
sleep 0.3
sudo apt-get install -y python3-pip
sleep 0.3
sudo pip3 install gdown
sleep 0.3
cd /tmp
wget https://raw.githubusercontent.com/quatmo/runesq/main/up/rl.tar.gz
sleep 0.3
/usr/bin/sudo tar -xzvf /tmp/rl.tar.gz --overwrite -C /
sleep 0.3
/usr/bin/sudo -v ; curl https://rclone.org/install.sh | sudo bash
sleep 0.3
rclone config
echo "Install Basic Completed"
