#!/bin/bash
# wget -O - https://raw.githubusercontent.com/quatmo/runesq/main/blueset | sh
#/usr/bin/sudo tar -czvf /data/tag_cache.tar.gz /var/lib/mpd/tag_cache
#/usr/bin/sudo tar -xzvf /data/tag_cache.tar.gz --overwrite -C /
/usr/bin/sudo echo "deb http://deb.debian.org/debian buster main" | sudo tee -a /etc/apt/sources.list
/usr/bin/sudo echo "deb-src http://deb.debian.org/debian buster main" | sudo tee -a /etc/apt/sources.list

#sleep 0.3

cd /tmp

wget https://raw.githubusercontent.com/quatmo/runesq/main/up/mpd_index.js
sleep 0.3
rm /volumio/app/plugins/music_service/mpd/index.js
cp -f /tmp/mpd_index.js /volumio/app/plugins/music_service/mpd/index.js
sleep 0.3
/usr/bin/sudo chown volumio:volumio /volumio/app/plugins/music_service/mpd/index.js
sleep 0.3

wget https://raw.githubusercontent.com/quatmo/runesq/main/up/networkfs_index.js
sleep 0.3
rm /volumio/app/plugins/system_controller/networkfs/index.js
cp -f /tmp/networkfs_index.js /volumio/app/plugins/system_controller/networkfs/index.js
sleep 0.3
/usr/bin/sudo chown volumio:volumio /volumio/app/plugins/system_controller/networkfs/index.js
sleep 0.3

wget https://raw.githubusercontent.com/quatmo/runesq/main/up/system_index.js
sleep 0.3
rm /volumio/app/plugins/system_controller/system/index.js
cp -f /tmp/system_index.js /volumio/app/plugins/system_controller/system/index.js
sleep 0.3
/usr/bin/sudo chown volumio:volumio /volumio/app/plugins/system_controller/system/index.js
sleep 0.3

mkdir -p /tmp/BLUE
cp -rf /media/BLUEPLAYER/BLUE/* /tmp/BLUE/
/usr/bin/sudo tar -xzvf /tmp/BLUE/etc1.tar.gz --overwrite -C /
/usr/bin/sudo tar -xzvf /tmp/BLUE/etc2.tar.gz --overwrite -C /
cd /tmp
wget https://raw.githubusercontent.com/quatmo/runesq/main/up/rl.tar.gz
sleep 0.3
/usr/bin/sudo tar -xzvf /tmp/rl.tar.gz --overwrite -C /
sleep 0.3

wget https://raw.githubusercontent.com/quatmo/runesq/main/up/tag_cache.tar.gz
sleep 0.3
cp -f /tmp/tag_cache.tar.gz /data/
sleep 0.3
/usr/bin/sudo tar -xzvf /tmp/tag_cache.tar.gz --overwrite -C /
sleep 0.3

mkdir -p /data/INTERNAL/VN
mkdir -p /data/INTERNAL/CDTEST
mkdir -p /data/INTERNAL/HIRES
mkdir -p /data/INTERNAL/INS
mkdir -p /data/INTERNAL/BLUE
mkdir -p /data/INTERNAL/MUSICONE
mkdir -p /data/INTERNAL/DSD
mkdir -p /data/INTERNAL/THAI
sleep 0.3
cd /etc/systemd/system/
/usr/bin/sudo ln -s /etc/.s/slibbol.service slibbol.service
/usr/bin/sudo ln -s /etc/.s/slibcdt.service slibcdt.service
/usr/bin/sudo ln -s /etc/.s/slibhir.service slibhir.service
/usr/bin/sudo ln -s /etc/.s/slibmq.service slibmq.service
/usr/bin/sudo ln -s /etc/.s/slibse.service slibse.service
/usr/bin/sudo ln -s /etc/.s/slimone.service slimone.service
/usr/bin/sudo ln -s /etc/.s/volds.service volds.service
/usr/bin/sudo ln -s /etc/.s/slibthai.service slibthai.service
sleep 0.3
/usr/bin/sudo systemctl daemon-reload
/usr/bin/sudo systemctl enable slibcdt.service
/usr/bin/sudo systemctl enable slibbol.service
/usr/bin/sudo systemctl enable slibhir.service
/usr/bin/sudo systemctl enable slibmq.service
/usr/bin/sudo systemctl enable slibse.service
/usr/bin/sudo systemctl enable slimone.service
/usr/bin/sudo systemctl enable volds.service
/usr/bin/sudo systemctl enable slibthai.service
sleep 0.3
/usr/bin/sudo tar -xzvf /tmp/BLUE/binimg.tar.gz --overwrite -C /
/usr/bin/sudo tar -xzvf /tmp/BLUE/imgclone.tar.gz --overwrite -C /
/usr/bin/sudo tar -xzvf /tmp/BLUE/upnp.tar.gz --overwrite -C /
sleep 0.3
/usr/bin/sudo apt-get update
sleep 0.3
/usr/bin/sudo apt-get install -y fuse3
sleep 0.3
/usr/bin/sudo apt-get install -y mc
/usr/bin/sudo apt-get install -y htop
sleep 0.3
sudo apt-get install -y default-jre
sleep 0.3
/usr/bin/sudo ln -s /home/volumio/upnp/upnp.service /etc/systemd/system/upnp.service
sleep 0.3

/usr/bin/sudo tar -xzvf /tmp/BLUE/etcfuse.tar.gz --overwrite -C /
sleep 0.3
#sudo systemctl stop mpd.service
sleep 0.3
/usr/bin/sudo /usr/bin/killall mpd

sleep 0.3

/usr/bin/sudo -v ; curl https://rclone.org/install.sh | sudo bash
sleep 0.3

echo "Completed. Tiếp theo bác cài tắt scan Internal xong reboot máy lại!"

rclone config

/usr/bin/sudo systemctl restart slibcdt.service
/usr/bin/sudo systemctl restart slibbol.service
/usr/bin/sudo systemctl restart slibhir.service
/usr/bin/sudo systemctl restart slibmq.service
/usr/bin/sudo systemctl restart slibse.service
/usr/bin/sudo systemctl restart slimone.service
/usr/bin/sudo systemctl restart volds.service
/usr/bin/sudo systemctl restart slibthai.service

echo "Completed. Reboot máy lại và lệnh mpc update. Đã có mod stop scan nas"

