#!/bin/bash
# wget -O - https://raw.githubusercontent.com/quatmo/runesq/main/blueset | sh
# nen sudo tar -czvf xx.tar.gz
# gnen sudo tar -xzvf --overwrite -C /
mkdir -p /tmp/BLUE
cp -rf /media/BLUEPLAYER/BLUE/* /tmp/BLUE/
/usr/bin/sudo tar -xzvf /tmp/BLUE/etc1.tar.gz --overwrite -C /
/usr/bin/sudo tar -xzvf /tmp/BLUE/etc2.tar.gz --overwrite -C /
cd /tmp
sleep 0.3
mkdir -p /data/INTERNAL/VN
mkdir -p /data/INTERNAL/CDTEST
mkdir -p /data/INTERNAL/HIRES
mkdir -p /data/INTERNAL/INS
mkdir -p /data/INTERNAL/BLUE
mkdir -p /data/INTERNAL/MUSICONE
mkdir -p /data/INTERNAL/DSD
mkdir -p /data/INTERNAL/TL
sleep 0.3
cd /etc/systemd/system/
/usr/bin/sudo ln -s /etc/.s/slibbol.service slibbol.service
/usr/bin/sudo ln -s /etc/.s/slibcdt.service slibcdt.service
/usr/bin/sudo ln -s /etc/.s/slibhir.service slibhir.service
/usr/bin/sudo ln -s /etc/.s/slibmq.service slibmq.service
/usr/bin/sudo ln -s /etc/.s/slibse.service slibse.service
/usr/bin/sudo ln -s /etc/.s/slimone.service slimone.service
/usr/bin/sudo ln -s /etc/.s/volds.service volds.service
/usr/bin/sudo ln -s /etc/.s/slibthai.service slibthai.service
sleep 0.3
/usr/bin/sudo systemctl daemon-reload
/usr/bin/sudo systemctl enable slibcdt.service
/usr/bin/sudo systemctl enable slibbol.service
/usr/bin/sudo systemctl enable slibhir.service
/usr/bin/sudo systemctl enable slibmq.service
/usr/bin/sudo systemctl enable slibse.service
/usr/bin/sudo systemctl enable slimone.service
/usr/bin/sudo systemctl enable volds.service
/usr/bin/sudo systemctl enable slibthai.service
sleep 0.3
/usr/bin/sudo tar -xzvf /tmp/BLUE/binimg.tar.gz --overwrite -C /
/usr/bin/sudo tar -xzvf /tmp/BLUE/imgclone.tar.gz --overwrite -C /
/usr/bin/sudo tar -xzvf /tmp/BLUE/upnp.tar.gz --overwrite -C /
sleep 0.3
/usr/bin/sudo apt-get update
sleep 0.3
/usr/bin/sudo apt-get install -y fuse3
sleep 0.3
/usr/bin/sudo apt-get install -y mc
/usr/bin/sudo apt-get install -y htop
sleep 0.3
sudo apt-get install -y default-jre
sleep 0.3
/usr/bin/sudo ln -s /home/volumio/upnp/upnp.service /etc/systemd/system/upnp.service
sleep 0.3

/usr/bin/sudo tar -xzvf /tmp/BLUE/etcfuse.tar.gz --overwrite -C /
sleep 0.3
#sudo systemctl stop mpd.service
sleep 0.3
/usr/bin/sudo /usr/bin/killall mpd

sleep 0.3
/usr/bin/sudo tar -xzvf /tmp/BLUE/tag_cache.tar.gz --overwrite -C /
sleep 0.3

/usr/bin/sudo -v ; curl https://rclone.org/install.sh | sudo bash
sleep 0.3
