#!/bin/bash
#wget -O - https://raw.githubusercontent.com/quatmo/runesq/main/busd | sh

# Add Debian Buster repositories
sudo sh -c 'echo "deb http://deb.debian.org/debian buster main" >> /etc/apt/sources.list'
sudo sh -c 'echo "deb-src http://deb.debian.org/debian buster main" >> /etc/apt/sources.list'

# Update the package list
sudo apt-get update

# Install required packages
sudo apt-get install -y gcc make git

# Clone imgclone repository
git clone https://github.com/tom-2015/imgclone.git

# Navigate to imgclone directory
cd imgclone

# Build imgclone
make

# Install imgclone
sudo make install

echo "Install completed successfully."

#read -p "Please enter USB disk name: " usb_name && read -p "Please enter IMG file name: " file_name && cd /media/"$usb_name" && sudo imgclone -x 524288000 -d "$file_name.img"
