#!/bin/bash
# wget -O - https://raw.githubusercontent.com/quatmo/runesq/main/docm | sh
wget https://raw.githubusercontent.com/quatmo/runesq/main/up/mpd_index.js
sleep 0.3
cp -f /volumio/app/plugins/music_service/mpd/index.js /volumio/app/plugins/music_service/mpd/index_O.js
rm /volumio/app/plugins/music_service/mpd/index.js
cp -f /tmp/mpd_index.js /volumio/app/plugins/music_service/mpd/index.js
sleep 0.3
/usr/bin/sudo chown volumio:volumio /volumio/app/plugins/music_service/mpd/index.js
sleep 0.3

wget https://raw.githubusercontent.com/quatmo/runesq/main/up/networkfs_index.js
cp -f /volumio/app/plugins/system_controller/networkfs/index.js /volumio/app/plugins/system_controller/networkfs/index_O.js
sleep 0.3
rm /volumio/app/plugins/system_controller/networkfs/index.js
cp -f /tmp/networkfs_index.js /volumio/app/plugins/system_controller/networkfs/index.js
sleep 0.3
/usr/bin/sudo chown volumio:volumio /volumio/app/plugins/system_controller/networkfs/index.js
sleep 0.3

wget https://raw.githubusercontent.com/quatmo/runesq/main/up/system_index.js
cp -f /volumio/app/plugins/system_controller/system/index.js /volumio/app/plugins/system_controller/system/index_O.js
sleep 0.3
rm /volumio/app/plugins/system_controller/system/index.js
cp -f /tmp/system_index.js /volumio/app/plugins/system_controller/system/index.js
sleep 0.3
/usr/bin/sudo chown volumio:volumio /volumio/app/plugins/system_controller/system/index.js
sleep 0.3
echo "Completed"
