#!/bin/bash
cd /tmp
#chmod -R 755 /tmp/ins.sh && cd /tmp/ && ./ins.sh

if [ -d "/opt/logitechmediaserver-git" ]; then
    systemctl stop logitechmediaserver-git.service
fi
if [ -d "/opt/sq" ]; then
    systemctl stop sq.service
fi
if [ -e /etc/systemd/system/tidal.service ]; then
    systemctl stop tidal.service
    systemctl disable tidal.service
    rm -f /etc/systemd/system/tidal.service
fi

if grep -q "dtparam=audio=on" /boot/config.txt; then
sudo sed -i '/dtparam=audio=on/d' /boot/config.txt
else
echo "No dtparam=audio=on"
fi

echo "Off the sound onboard"
grep -q "dtparam=audio=off" /boot/config.txt
if [ $? -eq 0 ]; then
echo "onboard off"
else
echo "dtparam=audio=off" | sudo tee -a /boot/config.txt
echo "onboard to off"
fi

echo "Install Lib"
rm -f /var/lib/pacman/sync/*
pacman -Syu --noconfirm --ignore dhcpcd
sleep 0.3
pacman -S --noconfirm perl
pacman -S --noconfirm perl-io-socket-ssl
pacman -S --noconfirm perl-net-ssleay
pacman -S --noconfirm perl-uri
sleep 0.3
pacman -S --noconfirm faad2
pacman -S --noconfirm libmad
pacman -S --noconfirm mpg123
pacman -S --noconfirm flac libvorbis
sleep 0.3
echo "Docker"
pacman --noconfirm -S git
pacman --noconfirm -S docker-compose
pacman --noconfirm -S docker
sleep 0.3

wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/logitechmediaserver-64.pkg.tar.xz
wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/sq.service
wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/sq.sh
wget https://raw.githubusercontent.com/lovehifi/raudiolms-64bit/main/sq64.tgz
wget https://raw.githubusercontent.com/quatmo/runesq/main/config.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/eqfa12.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/bub.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/Player.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/Linux.tar.gz
wget https://raw.githubusercontent.com/lovehifi/eqfa12/main/caps.tar.gz
wget https://raw.githubusercontent.com/lovehifi/eqfa12/main/ladspa_share.tar.gz
wget https://raw.githubusercontent.com/lovehifi/eqfa12/main/ladspa_usr.tar.gz
wget https://raw.githubusercontent.com/lovehifi/tidal-raudio-pi4/main/entrypoint.sh
wget https://raw.githubusercontent.com/lovehifi/tidal-raudio-pi4/main/tidal.service
wget https://raw.githubusercontent.com/lovehifi/tidal-raudio-pi4/main/env
wget https://raw.githubusercontent.com/lovehifi/tidal-raudio-pi4/main/docker-compose.yaml
wget https://raw.githubusercontent.com/lovehifi/eqfa12/main/eqfa12p.conf
wget https://raw.githubusercontent.com/lovehifi/eqfa12/main/eq12.conf
sleep 0.3

getent group logitechms &>/dev/null || groupadd -r logitechms >/dev/null
getent passwd logitechms &>/dev/null || useradd -r -g logitechms -d /opt/logitechmediaserver-git -c 'Logitech Media Server' -s /bin/false logitechms >/dev/null
mkdir -p /opt/logitechmediaserver-git/{cache,Logs,prefs{,/plugin},Plugins}
touch /opt/logitechmediaserver-git/Logs/slimserver.log
sleep 0.3
git clone https://github.com/GioF71/tidal-connect.git
sleep 0.3

echo "Install"
pacman -U --noconfirm /tmp/logitechmediaserver-64.pkg.tar.xz
tar -xzvf /tmp/sq64.tgz --overwrite -C /opt/
sleep 0.3
cp -f /tmp/sq.service /etc/systemd/system/
cp -f /tmp/sq.sh /opt/sq/
sleep 0.3
tar -xzvf /tmp/config.tar.gz --overwrite -C /
tar -xzvf /tmp/eqfa12.tar.gz --overwrite -C /
tar -xzvf /tmp/bub.tar.gz --overwrite -C /
tar -xzvf /tmp/Player.tar.gz --overwrite -C /
tar -xzvf /tmp/Linux.tar.gz --overwrite -C /
sleep 0.3
tar -xzvf /tmp/caps.tar.gz --overwrite -C /
tar -xzvf /tmp/ladspa_share.tar.gz --overwrite -C /
tar -xzvf /tmp/ladspa_usr.tar.gz --overwrite -C /
sleep 0.3
systemctl daemon-reload
systemctl start docker.service
systemctl enable docker.service
sleep 0.3
sleep 0.3
mv -f /tmp/tidal-connect /root/
sleep 0.3

cp -f /tmp/entrypoint.sh /root/tidal-connect/bin/
cp -f /tmp/tidal.service /etc/systemd/system/
cp -f /tmp/env /root/tidal-connect/.env
cp -f /tmp/docker-compose.yaml /root/tidal-connect/
cd /root/tidal-connect
git pull

echo "Build Docker"
docker-compose up -d
#docker-compose up -d --force-recreate
sleep 1
echo "Remove the text ipv6.disable=1 in /boot/cmdline.txt"
cp /boot/cmdline.txt /boot/cmdline.txt.backup && sed -i '0,/ipv6.disable=1/{s/ipv6.disable=1//}' /boot/cmdline.txt
sleep 1

if grep -q "dtparam=audio=on" /boot/config.txt; then
sudo sed -i '/dtparam=audio=on/d' /boot/config.txt
else
echo "No dtparam=audio=on"
fi

echo "Off the sound onboard"
grep -q "dtparam=audio=off" /boot/config.txt
if [ $? -eq 0 ]; then
echo "onboard off"
else
echo "dtparam=audio=off" | sudo tee -a /boot/config.txt
echo "onboard to off"
fi

lines_to_check=(
    "hdmi_force_hotplug=1"
    "hdmi_group=2"
    "hdmi_mode=1"
    "hdmi_mode=87"
    "hdmi_cvt 800 480 60 6 0 0 0"
    "gpio=22=op,dh"
)
config_file="/boot/config.txt"
for line in "${lines_to_check[@]}"; do
    if ! grep -q "$line" "$config_file"; then
        echo "$line" >> "$config_file"
    fi
done
echo "Configurations added"
chmod -R 755 /srv/http/config/unit/*.service
sleep 0.3
cp -f /srv/http/config/unit/*.service /etc/systemd/system/
sleep 0.3
chmod -R 755 /etc/systemd/system/sq.service
chmod -R 755 /opt/sq/sq.sh
chmod -R 755 /srv/http/config/unit/*.sh
chmod -R 755 /srv/http/eqfa12/unit/*.sh
chmod -R 755 /root/tidal-connect/bin/entrypoint.sh
chmod -R 755 /etc/systemd/system/tidal.service
sleep 0.3
chown -R logitechms:logitechms /opt/logitechmediaserver-git
echo 'logitechms ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers
echo 'http ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers
usermod -a -G audio http
usermod -a -G audio logitechms
sleep 0.3
sudo localectl set-locale LANG=en_US.UTF-8
echo "Finished, the LMS at port 9000"
input_file="/etc/alsa/conf.d/eqfa12p.conf"
output_file="/tmp/eqfa12p_modified.conf"
file="/srv/http/data/mpdconf/output.conf"
sleep 0.3
cp -f /tmp/eqfa12p.conf /etc/alsa/conf.d/
cp -f /etc/alsa/conf.d/eqfa12p.conf /etc/alsa/conf.d/eqfa12p.conf.backup
cp -f /tmp/eq12.conf /srv/http/data/mpdconf/
sleep 0.3
if [ -f "$file" ]; then
  device=$(awk -F'"' '/device/ {gsub("hw:", "", $2); print $2; exit}' "$file")
  echo "Device: $device"
else
  echo "File not found: $file"
fi

if [ -f "$input_file" ]; then
  sed "s/plughw:[0-9]\+,[0-9]\+/plughw:$device/g" "$input_file" > "$output_file"
else
  echo "Input file not found: $input_file"
fi

cp -f /tmp/eqfa12p_modified.conf /etc/alsa/conf.d/eqfa12p.conf
sleep 0.3
cd ~
wget -O - https://raw.githubusercontent.com/lovehifi/lms-modern-skin/main/install.sh | sh
sleep 0.3
echo 'MOZ_USE_XINPUT2 DEFAULT=1' | sudo tee -a /etc/security/pam_env.conf

echo "Installation completed."
systemctl daemon-reload
sleep 0.3
systemctl enable sq.service
systemctl enable logitechmediaserver-git.service
sleep 0.3
systemctl disable localbrowser.service

