#!/bin/bash
# wget -O - https://raw.githubusercontent.com/quatmo/runesq/main/plugin | sh
git clone https://github.com/volumio/volumio-plugins-sources.git
cd volumio-plugins-sources.git
cd spotify
volumio plugin install
echo y
cd ..
cd touch_display
volumio plugin install
echo y
cd ..
