#!/bin/bash


# Đọc số phiên bản từ tệp update.ini
update_version=$(grep 'number' /srv/http/config/update.ini | awk -F'=' '/number/{print $2}' | tr -d ' ')

# Cập nhật số phiên bản trong tệp version.ini bằng số phiên bản mới
/usr/bin/sudo awk -v new_version="$update_version" -F'=' '/\[version\]/{f=1} f==1 && $1=="number" {$0=$1"="new_version} 1' /srv/http/config/version.ini > /srv/http/config/version_temp.ini

# Di chuyển tệp tạm thời version.ini về tệp gốc
/usr/bin/sudo mv /srv/http/config/version_temp.ini /srv/http/config/version.ini

/usr/bin/sudo chown http:http /srv/http/config/version.ini

echo "Số phiên bản trong tệp version.ini đã được cập nhật thành $update_version"

cd /tmp
wget https://raw.githubusercontent.com/quatmo/runesq/main/index.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/scriptytube.tar.gz
sleep 1
tar -xzvf /tmp/index.tar.gz --overwrite -C /
sleep 1
tar -xzvf /tmp/scriptytube.tar.gz --overwrite -C /
cd /tmp
wget https://raw.githubusercontent.com/quatmo/runesq/main/update.ini
cp -f /tmp/update.ini /srv/http/config/
/usr/bin/sudo chown http:http /srv/http/config/update.ini

find /root/.mozilla/firefox/*.default-release -name prefs.js -exec sed -i 's/user_pref("media.autoplay.default",.*/user_pref("media.autoplay.default", 0);/' {} +

/usr/bin/sudo reboot

exit


#Thêm 3 thông báo khi nhấn nút Browser on LCD, Turn off LCD và Switch Screen.
