#!/bin/bash

update_version=$(grep 'number' /srv/http/config/update.ini | awk -F'=' '/number/{print $2}' | tr -d ' ')

/usr/bin/sudo awk -v new_version="$update_version" -F'=' '/\[version\]/{f=1} f==1 && $1=="number" {$0=$1"="new_version} 1' /srv/http/config/version.ini > /srv/http/config/version_temp.ini

/usr/bin/sudo mv /srv/http/config/version_temp.ini /srv/http/config/version.ini

/usr/bin/sudo chown http:http /srv/http/config/version.ini

echo "version.ini $update_version"

cd /tmp
wget https://raw.githubusercontent.com/quatmo/runesq/main/scriptytube10.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/bubv9.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/index6.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/startLCD16.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/hdmipixel3.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/hdmi_drive.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/xorg1.tar.gz
wget https://raw.githubusercontent.com/quatmo/runesq/main/script_ad1.tar.gz
sleep 0.5
tar -xzvf /tmp/index6.tar.gz --overwrite -C /
sleep 0.5
tar -xzvf /tmp/scriptytube10.tar.gz --overwrite -C /
sleep 0.5
tar -xzvf /tmp/startLCD16.tar.gz --overwrite -C /
sleep 0.5
tar -xzvf /tmp/bubv9.tar.gz --overwrite -C /
sleep 0.5
tar -xzvf /tmp/hdmipixel3.tar.gz --overwrite -C /
sleep 0.5
tar -xzvf /tmp/hdmi_drive.tar.gz --overwrite -C /
tar -xzvf /tmp/script_ad1.tar.gz --overwrite -C /
cp -f /tmp/xorg1.tar.gz /srv/http/config/unit/
sleep 0.5
/usr/bin/sudo chown http:http /srv/http/config/unit/xorg1.tar.gz

sleep 0.5


/usr/bin/sudo /usr/bin/systemctl stop localbrowser.service
/usr/bin/sudo chown -Rv http:http /root/.mozilla/firefox/*/prefs.js
/usr/bin/sudo chown -Rv http:http /root/.mozilla/firefox/*/user.js
/usr/bin/sudo chown -Rv http:http /root/.mozilla/firefox/*.default-release/*.json

#find /root/.mozilla/firefox/*.default-release -name prefs.js -exec sed -i 's/user_pref("media.autoplay.default",.*/user_pref("media.autoplay.default", 0);/' {} +
/usr/bin/sudo sed -i '/user_pref("media.autoplay.default",/d' /root/.mozilla/firefox/*.default-release/prefs.js
/usr/bin/sudo sed -i '/user_pref("media.autoplay.default",/d' /root/.mozilla/firefox/*.default-release/user.js
sleep 1
echo 'user_pref("media.autoplay.default", 0);' | /usr/bin/sudo tee -a /root/.mozilla/firefox/*.default-release/prefs.js
sleep 1
echo 'user_pref("media.autoplay.default", 0);' | /usr/bin/sudo tee -a /root/.mozilla/firefox/*.default-release/user.js
echo 'user_pref("media.autoplay.default", 0);' >> /root/.mozilla/firefox/*.default-release/user.js
sleep 1

/usr/bin/sudo sed -i 's/gpu_mem=32/gpu_mem=64/' /boot/config.txt
/usr/bin/sudo sed -i '/hdmi_/d' "/boot/config.txt"
if grep -q "dtoverlay=vc4-fkms-v3d" "/boot/config.txt"; then
    /usr/bin/sudo sed -i '/dtoverlay=vc4-fkms-v3d/d' "/boot/config.txt"
fi
if grep -q "max_framebuffers=2" "/boot/config.txt"; then
    /usr/bin/sudo sed -i '/max_framebuffers=2/d' "/boot/config.txt"
fi

config_1="hdmi_drive=2
hdmi_force_hotplug=1
hdmi_force_mode=1
hdmi_group=1
hdmi_mode=4"
echo "$config_1" >> "/boot/config.txt"

cd /tmp
wget https://raw.githubusercontent.com/quatmo/runesq/main/update.ini
cp -f /tmp/update.ini /srv/http/config/
/usr/bin/sudo chown http:http /srv/http/config/update.ini

#rm -f /root/.mozilla/firefox/*.default-release/extensions_temp1a.json
#rm -f /root/.mozilla/firefox/*.default-release/extensions_temp2a.json
#rm -f /root/.mozilla/firefox/*.default-release/extensions_temp3a.json
#rm -f /root/.mozilla/firefox/*.default-release/extensions_temp4a.json

/usr/bin/sudo reboot

exit


#Thêm 3 thông báo khi nhấn nút Browser on LCD, Turn off LCD và Switch Screen.
